end?

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -3,5 +3,17 @@
 # build functions(api)
 yarn webpack
 
+if [ $? -ne 0 ]
+then
+  echo "can't build functions(api)"
+  exit 1
+fi
+
 # build dist(client)
 yarn elm make client/Main.elm --optimize --output=dist/index.html
+
+if [ $? -ne 0 ]
+then 
+  echo "can't build dist(client)"
+  exit 1
+fi
diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -3,8 +3,26 @@
 # Lint
 yarn run lint
 
+if [ $? -ne 0 ]
+then
+  echo "lint error"
+  exit 1
+fi
+
 # Unit Test
 yarn run test:unit
 
+if [ $? -ne 0 ]
+then
+  echo "Unit Test Failed"
+  exit 1
+fi
+
 # Format
 yarn run format
+
+if [ $? -ne 0 ]
+then
+  echo "Format Failed"
+  exit 1
+fi
